libs = [
    ("dotenv",                   "python-dotenv",            True),
    ("rich",                     "rich",                     True),
    ("edge_tts",                 "edge-tts",                 True),
    ("pyttsx3",                  "pyttsx3",                  True),
    ("openai",                   "openai",                   True),
    ("groq",                     "groq",                     True),
    ("sounddevice",              "sounddevice",              True),
    ("soundfile",                "soundfile",                True),
    ("playsound",                "playsound",                True),
    ("pyautogui",                "pyautogui",                True),
    ("psutil",                   "psutil",                   True),
    ("pycaw",                    "pycaw",                    False),
    ("screen_brightness_control","screen-brightness-control",False),
    ("flask",                    "flask",                    True),
    ("websockets",               "websockets",               True),
    ("requests",                 "requests",                 True),
    ("bs4",                      "beautifulsoup4",           True),
    ("schedule",                 "schedule",                 True),
]